SELECT O.ONAME AS 'OWNER', PER.PERPHONE AS 'PHONE_NO', P.PURCH_DATE AS 'PURCHASE_DATE'
FROM OWNERS AS O, PURCHASE AS P, PERSON AS PER
WHERE (DATEPART(MM, GETDATE()) - DATEPART(MM, P.PURCH_DATE) = 1) AND P.BUYER_ID = PER.PSSN AND PER.PSSN = O.SSN;