SELECT A.MOD_NO, REGNO
FROM AIRPLANE A
WHERE
A.REGNO NOT IN (SELECT O.AIRREG
			FROM OWNS O
			JOIN CORPORATION C ON C.SSN = O.OSSN)
			AND
A.REGNO NOT IN (
			SELECT W.EMP_NO
			FROM WORKS_ON W
			JOIN EMPLOYEE E ON W.EMP_NO= E.EID
			WHERE E.SHIFT = 'MORNING');
