SELECT PNAME AS NAME, PADD AS ADDRESS, PSSN
FROM PERSON AS P
JOIN OWNERS AS O ON O.SSN = P.PSSN
JOIN PURCHASE AS PC ON P.PSSN = PC.BUYER_ID
JOIN CORPORATION AS C ON C.SSN = PC.SELLER_ID
JOIN PLANE_TYPE AS PT ON PT.MODEL = PC.MOD
JOIN AIRPLANE AS A ON A.MOD_NO = PT.MODEL
JOIN OWNS AS OH ON (OH.OSSN = C.SSN) AND (DATEPART(MM, GETDATE()) - DATEPART(MM, PC.PURCH_DATE) = 1)
WHERE (DATEPART(MM, GETDATE()) - DATEPART(MM, OH.PURCHASE_DATE) = 1);
