SELECT DISTINCT PNAME AS NAME
FROM  EMPLOYEE AS E, PERSON AS P
INNER JOIN PURCHASE AS PC ON PC.BUYER_ID = P.PSSN
INNER JOIN AIRPLANE AS A ON A.MOD_NO = PC.MOD
INNER JOIN PLANE_SERVICE AS PS ON PS.A_SERVICE = A.REGNO
WHERE PS.STATUS_ = 'Ongoing' AND E.EID NOT IN (SELECT E.EID
FROM PLANE_SERVICE
);