SELECT DISTINCT
P.PILID AS PILOT_ID, P.PNAME AS PILOT_NAME, PS.STATUS_ AS MAINTENANCE_STATUS
FROM PILOT P 
JOIN FLIES F ON P.PILID = F.P_ID
JOIN AIRPLANE A ON F.AIRMOD  = A.MOD_NO
JOIN PLANE_SERVICE PS ON PS.A_SERVICE = A.REGNO
WHERE PS.STATUS_ = 'ONGOING';
