SELECT A.REGNO AS AIRPLANE_REGISTERATION, A.MOD_NO AS AIRPLANE_MODEL, AVG(P.HOURS_WORKED) AS AVG_HOURS_SERVICE
FROM PLANE_SERVICE P 
INNER JOIN AIRPLANE A ON A.REGNO = P.A_SERVICE
GROUP BY A.MOD_NO, A.REGNO;